server:
  port: 8095
spring:
  cloud:
    gateway:
      routes:
      - id: users-status
        uri: lb://resource-server
        predicates:
          - Path=/users/status/check
          - Method=GET
        filters:
          - RemoveRequestHeader=Cookie
      - id: albums
        uri: lb://albums
        predicates:
          - Path=/albums
          - Method=GET
        filters:
          - RemoveRequestHeader=Cookie
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka